workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20.10.0
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Set up code signing (development)
        script: |
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  ios-simulator:
    name: iOS Simulator Build (No Signing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20.10.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Build for Simulator
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            build
    artifacts:
      - /tmp/xcodebuild_logs/*.log

  ios-unsigned:
    name: iOS Unsigned IPA (for Sideloadly)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20.10.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Build unsigned app
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive
      - name: Create unsigned IPA
        script: |
          mkdir -p build/Payload
          cp -r build/App.xcarchive/Products/Applications/App.app build/Payload/
          cd build && zip -r ChristmasTree-unsigned.ipa Payload
    artifacts:
      - build/*.ipa
